services:
  # Backend API service
  - type: web
    name: quantgen-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://navyasree2405:navyasree2405@clustertbp.qpknhdd.mongodb.net/
      - key: PORT
        value: 10000
    
  # Frontend static site
  - type: web
    name: quantgen-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /api/*
        destination: https://quantgen-api.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html