// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gauywtfjirbgblqmbsmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhdXl3dGZqaXJiZ2JscW1ic210Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NTMwNTUsImV4cCI6MjA2MTIyOTA1NX0.KI4vpRL6QcqFMOaPFeLTGn7AEqR5RSj-YEjOw5aIjiY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);